; https://projecteuler.net/problem=2
; Even Fibonacci numbers
; Problem 2

; Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

; By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


(defn fib_even_sum
    ([] (fib_even_sum 1))
    ([a] (fib_even_sum a (+ a 1) 0))
    ([a b sum]
        ; (print a " ")
        (if (> a 4000000)
            sum
            (fib_even_sum b (+ a b) (+ sum (if (even? b) b 0)   )    )
        )
    )
)
